### ISSUE TITLE
ERROR: too many failed passphrase attempts

### ISSUE THREAD

**Issue by cryptolululu** [Anchor-Protocol/airdropcli#1]
npm version 7.8.0
node version 12.22.0
terracli version 0.4.5-2-g0e568d0
go version go1.15.8 linux/amd64

`airdropcli x claim-airdrop --from test1 --gas auto --fees=100000uusd --verbose` returns below error despite test1 existing in keyring, and terracli in path. No prompt for password.

```EOF
EOF
EOF
ERROR: too many failed passphrase attempts
Error: Command failed: terracli keys show test1 -o json 
EOF
EOF
EOF
ERROR: too many failed passphrase attempts

    at checkExecSyncError (child_process.js:635:11)
    at Object.execSync (child_process.js:671:15)
    at CLIKey.loadAccountDetails (/usr/lib/node_modules/@anchor-protocol/airdropcli/node_modules/@terra-money/terra.js/dist/key/CLIKey.js:84:50)
    at CLIKey.get (/usr/lib/node_modules/@anchor-protocol/airdropcli/node_modules/@terra-money/terra.js/dist/key/CLIKey.js:94:22)
    at Command.<anonymous> (/usr/lib/node_modules/@anchor-protocol/airdropcli/dist/util.js:252:39)
    at Command.listener [as _actionHandler] (/usr/lib/node_modules/@anchor-protocol/airdropcli/node_modules/commander/index.js:426:31)
    at Command._parseCommand (/usr/lib/node_modules/@anchor-protocol/airdropcli/node_modules/commander/index.js:1002:14)
    at Command._dispatchSubcommand (/usr/lib/node_modules/@anchor-protocol/airdropcli/node_modules/commander/index.js:953:18)
    at Command._parseCommand (/usr/lib/node_modules/@anchor-protocol/airdropcli/node_modules/commander/index.js:970:12)
    at Command._dispatchSubcommand (/usr/lib/node_modules/@anchor-protocol/airdropcli/node_modules/commander/index.js:953:18) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 45 4f 46 0a 45 4f 46 0a 45 4f 46 0a 45 52 52 4f 52 3a 20 74 6f 6f 20 6d 61 6e 79 20 66 61 69 6c 65 64 20 70 61 73 73 70 68 72 61 73 65 20 61 74 74 65 ... 5 more bytes>
  ],
  pid: 994080,
  stdout: <Buffer >,
  stderr: <Buffer 45 4f 46 0a 45 4f 46 0a 45 4f 46 0a 45 52 52 4f 52 3a 20 74 6f 6f 20 6d 61 6e 79 20 66 61 69 6c 65 64 20 70 61 73 73 70 68 72 61 73 65 20 61 74 74 65 ... 5 more bytes>
}

**Comment by MSNTCS** [comment]
Unfortunately, CLIKey does not work outside of Mac OS.
